# Configuration de la connexion à la base de données.
spring:
  datasource:
    url: jdbc:h2:mem:recettes
    username: root
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true # Pour eviter que le script data.sql s'execute avant l'initialisation Hibernate.
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
  h2:
    console.enabled: true # Accès à la console H2 dans votre navigateur http://localhost:8080/h2-console

logging:
  level:
    org:
      hibernate:
        type: trace #Pour loguer les valeurs dans les requêtes sql